### ISSUE TITLE
Error A17

### ISSUE THREAD

**Issue by artfaal** [cuproPanda/Quarry#3]
Hello! Tried new update. it's great new features. But seems it not work property. Tryed mine quarry resource as default and have no problem. But when i try to get chiseled block, always show me message 'Failure' and no any chanse of getting that.
https://gist.github.com/HugsLibRecordKeeper/d4fa49e9b6dcd0c9b209512fd6908e8b

**Comment by cuproPanda** [comment]
Should be fixed now. Let me know if you still have the issue
