### ISSUE TITLE
Mod filename clarity

### ISSUE THREAD

**Issue by AngleWyrm** [cuproPanda/Quarry#4]
It's sometimes hard to pick out a mod in the mod files list/folders list due to the name being obfuscated with author names that ruin sort order and abbreviations that remove direct communication.

Some examples of hard-to-understand names are "OHU drop ships" which can't be found under the reasonable expectation of "drop ship," "MF A16," which gives almost no information that leads a person to understand -- let alone find -- that it is the "More Floors" mod, "RD floorBeautyRebalance" which can't be found under "floor," and "JTReplaceWalls" which isn't sorted to "replace walls."

An example of easy-to-understand naming is "Rimsenal - Federation," part of a series of Rimsenal mods in an expected place.

**Comment by cuproPanda** [comment]
How is "Quarry" hard to understand? It's a mod that adds a quarry
